// ============================================================
// DATA - Calculadora de Paneles Solares Perú
// ============================================================

const CIUDADES_PERU = [
  // NORTE
  {
    id: "tumbes",
    nombre: "Tumbes",
    region: "Norte",
    hsp: 5.8,
    lat: -3.57,
    long: -80.45,
    altitud: 12,
  },
  {
    id: "piura",
    nombre: "Piura",
    region: "Norte",
    hsp: 5.7,
    lat: -5.19,
    long: -80.63,
    altitud: 29,
  },
  {
    id: "chiclayo",
    nombre: "Chiclayo",
    region: "Norte",
    hsp: 5.5,
    lat: -6.77,
    long: -79.84,
    altitud: 27,
  },
  {
    id: "trujillo",
    nombre: "Trujillo",
    region: "Norte",
    hsp: 5.4,
    lat: -8.11,
    long: -79.03,
    altitud: 34,
  },
  {
    id: "cajamarca",
    nombre: "Cajamarca",
    region: "Sierra Norte",
    hsp: 5.9,
    lat: -7.16,
    long: -78.51,
    altitud: 2750,
  },
  {
    id: "chachapoyas",
    nombre: "Chachapoyas",
    region: "Nor-oriente",
    hsp: 4.8,
    lat: -6.23,
    long: -77.87,
    altitud: 2335,
  },
  {
    id: "iquitos",
    nombre: "Iquitos",
    region: "Nor-oriente",
    hsp: 4.5,
    lat: -3.75,
    long: -73.25,
    altitud: 126,
  },
  {
    id: "tarapoto",
    nombre: "Tarapoto",
    region: "San Martín",
    hsp: 4.9,
    lat: -6.49,
    long: -76.36,
    altitud: 356,
  },
  // CENTRO
  {
    id: "huaraz",
    nombre: "Huaraz",
    region: "Sierra Centro",
    hsp: 6.1,
    lat: -9.53,
    long: -77.53,
    altitud: 3052,
  },
  {
    id: "huanuco",
    nombre: "Huánuco",
    region: "Centro",
    hsp: 5.6,
    lat: -9.93,
    long: -76.24,
    altitud: 1819,
  },
  {
    id: "cerro_de_pasco",
    nombre: "Cerro de Pasco",
    region: "Sierra Centro",
    hsp: 6.3,
    lat: -10.68,
    long: -76.26,
    altitud: 4380,
  },
  {
    id: "lima",
    nombre: "Lima / Callao",
    region: "Costa Centro",
    hsp: 4.8,
    lat: -12.04,
    long: -77.03,
    altitud: 154,
  },
  {
    id: "ica",
    nombre: "Ica",
    region: "Costa Centro",
    hsp: 6.5,
    lat: -14.07,
    long: -75.73,
    altitud: 406,
  },
  {
    id: "pisco",
    nombre: "Pisco",
    region: "Costa Centro",
    hsp: 6.2,
    lat: -13.71,
    long: -76.2,
    altitud: 11,
  },
  {
    id: "huancayo",
    nombre: "Huancayo",
    region: "Sierra Centro",
    hsp: 5.8,
    lat: -12.07,
    long: -75.2,
    altitud: 3249,
  },
  {
    id: "ayacucho",
    nombre: "Ayacucho",
    region: "Sierra Sur-centro",
    hsp: 6.0,
    lat: -13.16,
    long: -74.22,
    altitud: 2761,
  },
  // SUR
  {
    id: "cusco",
    nombre: "Cusco",
    region: "Sierra Sur",
    hsp: 5.5,
    lat: -13.53,
    long: -71.97,
    altitud: 3399,
  },
  {
    id: "puno",
    nombre: "Puno",
    region: "Sierra Sur",
    hsp: 5.6,
    lat: -15.84,
    long: -70.02,
    altitud: 3825,
  },
  {
    id: "juliaca",
    nombre: "Juliaca",
    region: "Sierra Sur",
    hsp: 5.5,
    lat: -15.49,
    long: -70.13,
    altitud: 3824,
  },
  {
    id: "arequipa",
    nombre: "Arequipa",
    region: "Sierra Sur",
    hsp: 6.4,
    lat: -16.41,
    long: -71.54,
    altitud: 2335,
  },
  {
    id: "moquegua",
    nombre: "Moquegua",
    region: "Sur",
    hsp: 6.3,
    lat: -17.19,
    long: -70.94,
    altitud: 1410,
  },
  {
    id: "tacna",
    nombre: "Tacna",
    region: "Sur",
    hsp: 6.6,
    lat: -18.01,
    long: -70.25,
    altitud: 562,
  },
  {
    id: "puerto_maldonado",
    nombre: "Puerto Maldonado",
    region: "Sur-oriente",
    hsp: 4.6,
    lat: -12.6,
    long: -69.19,
    altitud: 256,
  },
  {
    id: "abancay",
    nombre: "Abancay",
    region: "Sierra Sur",
    hsp: 5.7,
    lat: -13.64,
    long: -72.88,
    altitud: 2377,
  },
];

const ELECTRODOMESTICOS_HOGAR = [
  {
    id: "refrigeradora_130",
    nombre: "Refrigeradora pequeña (130L)",
    potencia: 100,
    categoria: "Cocina",
    icono: "🧊",
  },
  {
    id: "refrigeradora_250",
    nombre: "Refrigeradora mediana (250L)",
    potencia: 140,
    categoria: "Cocina",
    icono: "🧊",
  },
  {
    id: "refrigeradora_400",
    nombre: "Refrigeradora grande (400L+)",
    potencia: 200,
    categoria: "Cocina",
    icono: "🧊",
  },
  {
    id: "television_32",
    nombre: 'Televisor LED 32"',
    potencia: 50,
    categoria: "Entretenimiento",
    icono: "📺",
  },
  {
    id: "television_50",
    nombre: 'Televisor LED 50"',
    potencia: 80,
    categoria: "Entretenimiento",
    icono: "📺",
  },
  {
    id: "television_65",
    nombre: 'Televisor Smart 65"',
    potencia: 120,
    categoria: "Entretenimiento",
    icono: "📺",
  },
  {
    id: "lavadora",
    nombre: "Lavadora automática",
    potencia: 500,
    categoria: "Lavandería",
    icono: "🫧",
  },
  {
    id: "microondas",
    nombre: "Microondas",
    potencia: 1000,
    categoria: "Cocina",
    icono: "♨️",
  },
  {
    id: "licuadora",
    nombre: "Licuadora",
    potencia: 400,
    categoria: "Cocina",
    icono: "🥤",
  },
  {
    id: "plancha_ropa",
    nombre: "Plancha de ropa",
    potencia: 1200,
    categoria: "Lavandería",
    icono: "👕",
  },
  {
    id: "ducha_electrica",
    nombre: "Ducha eléctrica",
    potencia: 3500,
    categoria: "Baño",
    icono: "🚿",
  },
  {
    id: "abanico",
    nombre: "Abanico / Ventilador",
    potencia: 60,
    categoria: "Climatización",
    icono: "🌀",
  },
  {
    id: "aire_acondicionado_12k",
    nombre: "Aire acondicionado 12,000 BTU",
    potencia: 1200,
    categoria: "Climatización",
    icono: "❄️",
  },
  {
    id: "aire_acondicionado_18k",
    nombre: "Aire acondicionado 18,000 BTU",
    potencia: 1800,
    categoria: "Climatización",
    icono: "❄️",
  },
  {
    id: "computadora_pc",
    nombre: "Computadora de escritorio",
    potencia: 200,
    categoria: "Tecnología",
    icono: "🖥️",
  },
  {
    id: "laptop",
    nombre: "Laptop / Notebook",
    potencia: 65,
    categoria: "Tecnología",
    icono: "💻",
  },
  {
    id: "router_wifi",
    nombre: "Router WiFi",
    potencia: 15,
    categoria: "Tecnología",
    icono: "📡",
  },
  {
    id: "cargadores",
    nombre: "Cargadores de celulares (x2)",
    potencia: 20,
    categoria: "Tecnología",
    icono: "🔌",
  },
  {
    id: "foco_led",
    nombre: "Foco LED (por unidad)",
    potencia: 10,
    categoria: "Iluminación",
    icono: "💡",
  },
  {
    id: "foco_fluorescente",
    nombre: "Foco fluorescente (por unidad)",
    potencia: 20,
    categoria: "Iluminación",
    icono: "💡",
  },
  {
    id: "terma_electrica",
    nombre: "Terma eléctrica",
    potencia: 1500,
    categoria: "Agua Caliente",
    icono: "🔥",
  },
  {
    id: "bomba_agua",
    nombre: "Bomba de agua doméstica",
    potencia: 750,
    categoria: "Agua",
    icono: "💧",
  },
  {
    id: "impresora",
    nombre: "Impresora",
    potencia: 50,
    categoria: "Tecnología",
    icono: "🖨️",
  },
  {
    id: "horno_electrico",
    nombre: "Horno eléctrico",
    potencia: 1500,
    categoria: "Cocina",
    icono: "🔲",
  },
  {
    id: "extractor_cocina",
    nombre: "Extractor de cocina",
    potencia: 150,
    categoria: "Cocina",
    icono: "💨",
  },
];

const EQUIPOS_EMPRESA = [
  {
    id: "computadora_oficina",
    nombre: "Computadora de oficina",
    potencia: 200,
    categoria: "Equipos Ofimáticos",
    icono: "🖥️",
  },
  {
    id: "laptop_empresa",
    nombre: "Laptop empresarial",
    potencia: 65,
    categoria: "Equipos Ofimáticos",
    icono: "💻",
  },
  {
    id: "servidor_rack",
    nombre: "Servidor rack (1U)",
    potencia: 500,
    categoria: "Servidores / IT",
    icono: "🗄️",
  },
  {
    id: "impresora_laser",
    nombre: "Impresora láser",
    potencia: 500,
    categoria: "Equipos Ofimáticos",
    icono: "🖨️",
  },
  {
    id: "fotocopiadora",
    nombre: "Fotocopiadora multifuncional",
    potencia: 1200,
    categoria: "Equipos Ofimáticos",
    icono: "📠",
  },
  {
    id: "aire_comercial_24k",
    nombre: "Aire acondicionado comercial 24,000 BTU",
    potencia: 2500,
    categoria: "Climatización",
    icono: "❄️",
  },
  {
    id: "aire_comercial_36k",
    nombre: "Aire acondicionado comercial 36,000 BTU",
    potencia: 3500,
    categoria: "Climatización",
    icono: "❄️",
  },
  {
    id: "refrigeradora_comercial",
    nombre: "Refrigeradora comercial / vitrina",
    potencia: 350,
    categoria: "Refrigeración",
    icono: "🧊",
  },
  {
    id: "cafetera_comercial",
    nombre: "Cafetera / dispensador agua",
    potencia: 1000,
    categoria: "Cocina Office",
    icono: "☕",
  },
  {
    id: "microondas_comercial",
    nombre: "Microondas comercial",
    potencia: 1500,
    categoria: "Cocina Office",
    icono: "♨️",
  },
  {
    id: "caja_registradora",
    nombre: "Caja registradora / POS",
    potencia: 30,
    categoria: "Comercio",
    icono: "🏧",
  },
  {
    id: "camara_cctv",
    nombre: "Cámara CCTV (por unidad)",
    potencia: 15,
    categoria: "Seguridad",
    icono: "📷",
  },
  {
    id: "central_alarma",
    nombre: "Central de alarma",
    potencia: 50,
    categoria: "Seguridad",
    icono: "🔔",
  },
  {
    id: "ups_empresarial",
    nombre: "UPS empresarial 1kVA",
    potencia: 900,
    categoria: "Servidores / IT",
    icono: "🔋",
  },
  {
    id: "switch_router",
    nombre: "Switch + Router empresarial",
    potencia: 60,
    categoria: "Servidores / IT",
    icono: "📡",
  },
  {
    id: "iluminacion_led_tubo",
    nombre: "Luminaria LED tubo T8 (por unidad)",
    potencia: 18,
    categoria: "Iluminación",
    icono: "💡",
  },
  {
    id: "motor_electrico_1hp",
    nombre: "Motor eléctrico 1 HP",
    potencia: 750,
    categoria: "Maquinaria",
    icono: "⚙️",
  },
  {
    id: "motor_electrico_3hp",
    nombre: "Motor eléctrico 3 HP",
    potencia: 2200,
    categoria: "Maquinaria",
    icono: "⚙️",
  },
  {
    id: "bomba_agua_comercial",
    nombre: "Bomba de agua comercial",
    potencia: 1500,
    categoria: "Agua",
    icono: "💧",
  },
  {
    id: "ascensor_pequeño",
    nombre: "Ascensor pequeño (2 pisos)",
    potencia: 5000,
    categoria: "Instalaciones",
    icono: "🛗",
  },
  {
    id: "compresor_aire",
    nombre: "Compresor de aire 5HP",
    potencia: 3700,
    categoria: "Maquinaria",
    icono: "🔧",
  },
  {
    id: "soldadora",
    nombre: "Soldadora eléctrica 200A",
    potencia: 5000,
    categoria: "Maquinaria",
    icono: "🔩",
  },
  {
    id: "torno_cnc",
    nombre: "Torno / CNC pequeño",
    potencia: 3000,
    categoria: "Maquinaria",
    icono: "🏭",
  },
  {
    id: "pantalla_publicidad",
    nombre: "Pantalla publicitaria LED",
    potencia: 500,
    categoria: "Comercio",
    icono: "📺",
  },
];

const EQUIPOS_INDUSTRIA = [
  {
    id: "motor_5hp",
    nombre: "Motor industrial 5 HP",
    potencia: 3700,
    categoria: "Motores",
    icono: "⚙️",
  },
  {
    id: "motor_10hp",
    nombre: "Motor industrial 10 HP",
    potencia: 7500,
    categoria: "Motores",
    icono: "⚙️",
  },
  {
    id: "motor_20hp",
    nombre: "Motor industrial 20 HP",
    potencia: 15000,
    categoria: "Motores",
    icono: "⚙️",
  },
  {
    id: "motor_50hp",
    nombre: "Motor industrial 50 HP",
    potencia: 37000,
    categoria: "Motores",
    icono: "⚙️",
  },
  {
    id: "compresor_industrial",
    nombre: "Compresor industrial 10HP",
    potencia: 7500,
    categoria: "Maquinaria",
    icono: "🔧",
  },
  {
    id: "horno_industrial",
    nombre: "Horno industrial eléctrico",
    potencia: 10000,
    categoria: "Maquinaria",
    icono: "🔥",
  },
  {
    id: "soldadora_industrial",
    nombre: "Soldadora MIG/TIG industrial",
    potencia: 8000,
    categoria: "Maquinaria",
    icono: "🔩",
  },
  {
    id: "torno_industrial",
    nombre: "Torno industrial CNC",
    potencia: 5500,
    categoria: "Maquinaria",
    icono: "🏭",
  },
  {
    id: "grua_puente",
    nombre: "Grúa puente eléctrica 5T",
    potencia: 12000,
    categoria: "Izamiento",
    icono: "🏗️",
  },
  {
    id: "bomba_industrial",
    nombre: "Bomba industrial 7.5HP",
    potencia: 5600,
    categoria: "Bombeo",
    icono: "💧",
  },
  {
    id: "ventilador_industrial",
    nombre: "Ventilador industrial",
    potencia: 2000,
    categoria: "Ventilación",
    icono: "🌀",
  },
  {
    id: "iluminacion_nave",
    nombre: "Luminaria industrial LED 100W",
    potencia: 100,
    categoria: "Iluminación",
    icono: "💡",
  },
  {
    id: "ups_industrial",
    nombre: "UPS industrial 10kVA",
    potencia: 8000,
    categoria: "Eléctrico",
    icono: "🔋",
  },
  {
    id: "aire_industrial",
    nombre: "Sistema de A/C industrial 5T",
    potencia: 20000,
    categoria: "Climatización",
    icono: "❄️",
  },
  {
    id: "bombeo_agricola",
    nombre: "Bomba de riego agrícola 5HP",
    potencia: 3700,
    categoria: "Agricola",
    icono: "🌱",
  },
  {
    id: "refrigeracion_camaras",
    nombre: "Cámara frigorífica industrial",
    potencia: 15000,
    categoria: "Refrigeración",
    icono: "🧊",
  },
];

const TIPOS_PANEL = [
  {
    id: "panel_400w",
    nombre: "Panel Monocristalino 400W",
    potencia: 400,
    eficiencia: 0.2,
    precio_usd: 180,
    dimensiones: "1.72m × 1.04m",
    descripcion: "Ideal para hogares pequeños y medianos",
    popularidad: "Más vendido",
    degradacion_anual: 0.005,
  },
  {
    id: "panel_450w",
    nombre: "Panel Monocristalino 450W",
    potencia: 450,
    eficiencia: 0.21,
    precio_usd: 200,
    dimensiones: "1.87m × 1.04m",
    descripcion: "Excelente balance precio-rendimiento",
    popularidad: "Recomendado",
    degradacion_anual: 0.005,
  },
  {
    id: "panel_550w",
    nombre: "Panel Bifacial 550W",
    potencia: 550,
    eficiencia: 0.22,
    precio_usd: 260,
    dimensiones: "2.26m × 1.13m",
    descripcion: "Para empresas y mayor generación",
    popularidad: "Empresas",
    degradacion_anual: 0.004,
  },
  {
    id: "panel_600w",
    nombre: "Panel TOPCon 600W",
    potencia: 600,
    eficiencia: 0.235,
    precio_usd: 300,
    dimensiones: "2.38m × 1.13m",
    descripcion: "Alta tecnología para industrias",
    popularidad: "Industrial",
    degradacion_anual: 0.003,
  },
];

const TIPOS_BATERIA = [
  {
    id: "sin_bateria",
    nombre: "Sin Baterías (On-Grid)",
    tipo: "on_grid",
    descripcion: "Conectado a la red eléctrica. Vende el excedente a Electro.",
    autonomia_horas: 0,
    precio_kwh_usd: 0,
    ciclos_vida: 0,
    icono: "⚡",
  },
  {
    id: "bateria_plomo",
    nombre: "Batería de Plomo-Ácido AGM",
    tipo: "off_grid",
    descripcion: "Más económica, requiere mantenimiento, 3-5 años de vida.",
    autonomia_horas: 8,
    precio_kwh_usd: 150,
    ciclos_vida: 500,
    icono: "🔋",
  },
  {
    id: "bateria_litio",
    nombre: "Batería de Litio (LiFePO4)",
    tipo: "hibrido",
    descripcion:
      "Alta durabilidad 10+ años, sin mantenimiento. Sistema híbrido.",
    autonomia_horas: 10,
    precio_kwh_usd: 400,
    ciclos_vida: 3000,
    icono: "⚡🔋",
  },
];

const TARIFAS_ELECTRICAS_PERU = {
  bt2: {
    nombre: "BT2 - Residencial",
    precio_kwh: 0.62,
    descripcion: "Uso doméstico / hogar",
  },
  bt3_comercial: {
    nombre: "BT3 - Comercial",
    precio_kwh: 0.68,
    descripcion: "Pequeños negocios",
  },
  bt4_industrial: {
    nombre: "BT4 - Industrial",
    precio_kwh: 0.55,
    descripcion: "Industria (cargo por demanda)",
  },
  mt3: {
    nombre: "MT3 - Media Tensión",
    precio_kwh: 0.48,
    descripcion: "Grandes empresas",
  },
};

const FACTOR_CO2_PERU = 0.5568; // kg CO2 / kWh (MINEM 2023)
const TIPO_CAMBIO_USD_PEN = 3.75; // Soles por dólar (referencial)
const VIDA_UTIL_SISTEMA = 25; // años

// Perfil de usos típicos para el asistente IA
const PERFILES_TIPICOS = {
  hogar_pequeno: {
    nombre: "Hogar pequeño (2-3 personas)",
    consumo_kwh: 150,
    descripcion: "Casa pequeña o departamento con electrodomésticos básicos",
  },
  hogar_mediano: {
    nombre: "Hogar mediano (4-5 personas)",
    consumo_kwh: 280,
    descripcion: "Casa con todos los electrodomésticos incluyendo laundry",
  },
  hogar_grande: {
    nombre: "Hogar grande / mansión (6+ personas)",
    consumo_kwh: 500,
    descripcion: "Casa grande con A/C, piscina y múltiples aparatos",
  },
  oficina_pequena: {
    nombre: "Oficina pequeña (5-10 personas)",
    consumo_kwh: 400,
    descripcion: "Oficina con PCs, impresoras y A/C básico",
  },
  oficina_mediana: {
    nombre: "Oficina mediana (10-30 personas)",
    consumo_kwh: 1200,
    descripcion: "Empresa con servidores, múltiples A/C y equipos",
  },
  restaurant: {
    nombre: "Restaurante / café",
    consumo_kwh: 800,
    descripcion: "Cocina industrial, refrigeración, iluminación y A/C",
  },
  tienda_retail: {
    nombre: "Tienda / retail",
    consumo_kwh: 600,
    descripcion: "Iluminación, A/C, refrigeración y cajas",
  },
  hotel_pequeno: {
    nombre: "Hotel pequeño (20 hab.)",
    consumo_kwh: 3000,
    descripcion: "Habitaciones, A/C, lavandería y cocina",
  },
  industria_pequena: {
    nombre: "Pequeña industria / taller",
    consumo_kwh: 5000,
    descripcion: "Motores, maquinaria y área de oficinas",
  },
  industria_mediana: {
    nombre: "Industria mediana",
    consumo_kwh: 15000,
    descripcion: "Planta con maquinaria pesada, hornos y sistemas industriales",
  },
};
